name: Test

on:
  push:
    branches: [main,working]

jobs:
  
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install PyQt5
        pip install cmake
        pip install pastaq
    - name: Compile resources
      run: |
        cd src
        pyrcc5 -o resources.py resources.qrc
        cd ..
    - name: Perform tests
      run: |
        python src/tests/tests_CI.py
