name: Test

on:
  push:
    branches: [main,working]

jobs:
  
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Perform tests
      run: |
        python src/tests/test.py
        python src/tests/tests_CI.py
